### ISSUE TITLE
Format the code with Prettier, resolve the errors from webpack console.

### ISSUE THREAD

**Issue by tocttou** [akata01/TodoApp_redux#1] opened 2018-03-09 15:27 UTC

**Comment by tocttou** [comment] 2018-03-09 15:28
Comment like this: 47d87751c29ea876af49ecf84c44ba638ac702d2

**Comment by tocttou** [comment] 2018-03-09 15:29
Comment like this: 47d8775

**Comment by akata01** [comment] 2018-03-09 15:32
yo ok

**Comment by akata01** [comment] 2018-03-10 18:37
When i was trying to push the committed changes after formatting the code with prettier using the command : git push -u githubRepo master and git push but both ways same error popped up .
The complete error is as follows:
$ git push -u githubRepo master
fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Username for 'https://github.com': akata01
To https://github.com/akata01/TodoApp_redux.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/akata01/TodoApp_redux.git                                                                                                                                                                                               '
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

So i rather used $ git push githubRepo master -f
and i guess this command force pushes the commits.

So, is it fine to use the force push command or do i need to first use the fetch command and then the push command.

**Comment by tocttou** [comment] 2018-03-11 12:36
If you make changes to the repo directly in some way, like editing on github directly or editing locally somewhere else and pushing from there => you need to pull the old work into your repo by doing `git pull origin master` before you start any new work. By doing the force push, the work that had caused this error will get overwritten and you may not want that.

**Comment by tocttou** [comment] 2018-03-11 12:57
One of the errors, `Parsing error: Unexpected token =` is because in line 35 of `AddTaskPage.js`, you are using "class properties", which is a new feature and you need to transpile it to the older way of doing things for it to work. This project does that using the `babel-plugin-transform-class-properties`, and thats why it works, but eslint doesn't know that. You need to add a plugin for it:

`npm i eslint-plugin-class-property --save-dev`
then in your `.eslintrc` file, add "class-property" in plugins, so it looks like:
```
{
    "plugins": [
        "react",
        "class-property"
    ]
}
```
Other errors are easy to resolve. Just add props validations where required. You may want to remove the rules `import/default` and `import/namespace` from `.eslintrc` file. To do this, add the following lines under "rules":
```
"import/default": 0,
"import/namespcae": 0
```
For other errors, google those rules and see what they mean and if you can correct them.

**Comment by akata01** [comment] 2018-03-11 17:24
Eslint class-property plugin is not resolving the `Parsing error: Unexpected token =` error. I guess there is no eslint plugin for this syntax yet. I tried installing `babel-eslint` that is a wrapper for Babel's parser used for esLint using `npm install babel-eslint --save-dev` and then included the  following lines in my .eslintrc file - `{
  "parser": "babel-eslint",
  "rules": {
    "strict": 0
  }
}`.
Th error then changed to `state not defined ` and all the functions defined using fat arrow syntax were shown undefined. To work around that, i added `"no-undef": 0` in eslint rules. Eslint now shows everything  clean but it is surely not :p . 
All other errors and warnings are resolved. Only the transform-class-properties syntax shows error , maybe because it is not yet supported by eslint.

**Closed** 2018-03-11 17:45 UTC

**Comment by tocttou** [comment] 2018-03-11 21:30
It must have been resolved by it. I'll check it soon,.
